name: "Terratest GitHub Action"
on:
  pull_request:
    branches: [test, dev, qa, prod, main]
  push:
    branches: [test, dev, qa, prod, main]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TERRATEST_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.TERRATEST_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  AWS_REGION: ${{ secrets.TERRATEST_AWS_REGION }}
  TF_VAR_google_project: ${{ secrets.TERRATEST_GOOGLE_PROJECT }}
  TF_VAR_google_credentials: ${{ secrets.TERRATEST_GOOGLE_CREDENTIALS }}
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run 'go test -v -timeout 60m'
        run: |
          cd test
          go mod download
          go test -v -timeout 30m
